### ISSUE TITLE
About the training process under the train_net.py

### ISSUE THREAD

**Issue by SorryGeats** [TQTQliu/MVSGaussian#25]
Hi, sir! I'm sorry to bother you again. While I run the train_net.py on my own dataset, I find that the log file where I redirect the output information is always increasing its storage, shown as below:
![image](https://github.com/user-attachments/assets/5d88f9a8-61e6-439b-8ecb-42d988882040)
What makes me confused is that whether the traning process needs such a long time to complete it.
It is appreciated of you to offer me some suggestions about it.
Looking forward to your earliest reply!

**Comment by TQTQliu** [comment]
Hello, this is because the default epoch is 300, you can change it in the [config file](https://github.com/TQTQliu/MVSGaussian/blob/aa5e786c865858f42c7942edd931cc3b79825628/configs/mvsgs/dtu_pretrain.yaml#L66), or add `train.epoch <the number of epochs>` to specify the epoch number, like:
```
python train_net.py --cfg_file configs/mvsgs/colmap_eval.yaml train_dataset.data_root examples/scene1 test_dataset.data_root examples/scene1 train.epoch <the number of epochs>
```
​Another point worth noting is that before training, the code will first check whether there is checkpoint in `trained_model/mvsgs/exp_name`, and if so, the latest checkpoint will be loaded.  Therefore, you can modify `exp_name` in the config file to control training from scratch or fine-tuning an existed pre-trained model.  Details can be found [here](https://github.com/TQTQliu/MVSGaussian?tab=readme-ov-file#train-generalizable-model), as follows:

You can specify the [`gpus`](https://github.com/TQTQliu/MVSGaussian/blob/823713141181fd68ef05ab188ed36bf7f1045ea5/configs/mvsgs/dtu_pretrain.yaml#L2) in `configs/mvsgs/dtu_pretrain.yaml`. And you can modify the [`exp_name`](https://github.com/TQTQliu/MVSGaussian/blob/823713141181fd68ef05ab188ed36bf7f1045ea5/configs/mvsgs/dtu_pretrain.yaml#L3) in the `configs/mvsgs/dtu_pretrain.yaml`. Before training, the code will first check whether there is checkpoint in `trained_model/mvsgs/exp_name`, and if so, the latest checkpoint will be loaded. During training, the tensorboard log will be save in `record/mvsgs/exp_name`, the trained checkpoint will be save in `trained_model/mvsgs/exp_name`, and the rendering results will be saved in `result/mvsgs/exp_name`.
