### ISSUE TITLE
Why the metric get lower after gaussian optimization satge?

### ISSUE THREAD

**Issue by ZhenyuSun-Walker** [TQTQliu/MVSGaussian#35]
Hi, sir. I wonder why the metrics decrease after the per-scene gaussian optimization?
For example/scene2, the metric decrease drastically, compared with the metrics after generalizable model.
![image](https://github.com/user-attachments/assets/76cfa352-1586-4d3f-a46d-462b9bca3f27)

**Comment by TQTQliu** [comment]
I guess you generated the video first and then measured the metrics. Because for scene2, there are only 4 target views when calculating metrics instead of 60. Since each frame of the generated video actually has no GT, the metrics measured at this time are meaningless.
You can delete the folder, re-render and calculate metrics.

**Comment by ZhenyuSun-Walker** [comment]
So I should delete the folder in the `result`?

**Comment by TQTQliu** [comment]
You can delete the folder `output/scene2/test`, and then re-run
```
python lib/render.py -c -m output/scene1 --iteration <iter> -p <path to save ply>
python lib/metrics.py -m output/scene1
```

**Comment by ZhenyuSun-Walker** [comment]
Thanks for your advice. It really helps me a lot.

**Comment by ZhenyuSun-Walker** [comment]
However, although your advice works, but the metric after the gaussian optimization is still a little bit lower than the one from the generalizable model.

**Comment by TQTQliu** [comment]
For some scenarios, Gaussian optimization may indeed not provide a performance boost because Gaussian tends to overfit the training views.
In this case, if you want to further improve performance, you can try another optimization method (optimizing the entire pipeline),  refer to [here](https://github.com/TQTQliu/MVSGaussian/blob/84ec6bbb81821848bc7a1defd61b26b9171a8167/README.md?plain=1#L282-L291).
