### ISSUE TITLE
Questions about how to build feature volumes

### ISSUE THREAD

**Issue by YuhsiHu** [TQTQliu/MVSGaussian#40]
Hi, thank you for your great work! 

I found that when building the feature volume in your code, the method is different from the commonly used method in MVSNet. The 'variance' and 'context' tensor are concat together [here](https://github.com/TQTQliu/MVSGaussian/blob/main/lib/networks/mvsgs/utils.py#L278). Usually, variance is enough to calculate the matching cost. Why is context additionally used? Will this be helpful for estimating depth or rendering images?

**Comment by TQTQliu** [comment]
Hi, thanks for your interest. 
In our experiments, we found that combining variance and context can slightly improve rendering quality. 
The intuitive interpretation is that synthesizing novel views requires predicting both rgb and volume density, where volume density corresponds to the geometry (depth) of the scene, which can be explicitly modeled by variance; RGB corresponds to the appearance characteristics of the scene, so adding context information will help decode RGB.

**Comment by TQTQliu** [comment]
Hi, I haven't tried using this concat strategy for MVS tasks, so I don't know if it improves the depth accuracy for MVS tasks. However, in our task, this strategy can slightly improve depth accuracy and view quality.
The mini-regularization of the first stage is to reduce the computational overhead, because the value of D is relatively large in the first stage.

**Comment by YuhsiHu** [comment]
Thank you very much for your explanation! I will close this issue.
