### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by kgkgkgjb** [TQTQliu/MVSGaussian#41]
Hi, thank you very much for your contribution!

python run.py --type evaluate --cfg_file configs/mvsgs/colmap_eval.yaml test_dataset.data_root examples/scene1
When I run this command, an error occurs：
Traceback (most recent call last):
  File "run.py", line 98, in <module>
    globals()['run_' + args.type]()
  File "run.py", line 78, in run_evaluate
    output = network(batch)
  File "/opt/conda/envs/mvsgs/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "lib/networks/mvsgs/network.py", line 111, in forward
    render_novel_i_0 = render(batch[f'novel_view{i}'], b_i, world_xyz[b_i], color_out[b_i], rot_out[b_i], scale_out[b_i], opacity_out[b_i], bg_color=cfg.mvsgs.bg_color)
  File "/workspace/MVSGaussian/lib/gaussian_renderer/__init__.py", line 61, in render
    cov3D_precomp=None)
ValueError: too many values to unpack (expected 2)

**Comment by TQTQliu** [comment]
Hi, thanks for your interest.
I just checked this problem and found that it is because the [Gaussian splatting](https://github.com/graphdeco-inria/gaussian-splatting) code was updated a few days ago. The updated [rasterizer](https://github.com/graphdeco-inria/gaussian-splatting/blob/21301643a4354d6e24495c0df5a85354af8bd2be/gaussian_renderer/__init__.py#L86) function will return three values instead of two, so this error `ValueError: too many values to unpack (expected 2)` occurred.

There are two solutions:
1) You can modify [this line](https://github.com/TQTQliu/MVSGaussian/blob/84ec6bbb81821848bc7a1defd61b26b9171a8167/lib/gaussian_renderer/__init__.py#L53), from `rendered_image, _ = rasterizer(` to `rendered_image, _, _ = rasterizer(` to avoid this error.

2) To prevent gaussian splatting from being updated further and resulting in incompatibility with our code, we upload the `submodules` folder. Therefore, you can also re-clone our repository and then install the `diff-gaussian-rasterization` and `simple-knn` with the following commands:
```
pip install lib/submodules/diff-gaussian-rasterization
pip install lib/submodules/simple-knn
```
You can also find updated instructions in [readme](https://github.com/TQTQliu/MVSGaussian#-installation).

**Comment by kgkgkgjb** [comment]
Thank you very much for your reply! The issue has been resolved
